name: Build and Publish .NET Application to App Service

on:
    push:
    workflow_dispatch:

env:
    DOTNET_VERSION: 8.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - uses: actions/checkout@v4
    
    # Setup .NET Sdk
    - name: Setup .NET 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    # Check File Structure
    - run: ls -R
  
    # Restore dependencies
    - name: Install dependencies
      run: dotnet restore ./Catalog.API/Catalog.API.csproj
    
    # Run dotnet build
    - name: Build with dotnet
      run: dotnet build ./Catalog.API/Catalog.API.csproj --configuration Release --no-restore

    # Run dotnet publish and store the artifacts in catalog/publish
    - name: Publish
      run: |
        dotnet publish ./Catalog.API/Catalog.API.csproj --configuration Release --no-build --output 'catalog/publish'
    
    # Check File Structure
    - run: ls -R