name: Build and Publish .NET Application to App Service

on:
    push:
    workflow_dispatch:

env:
    DOTNET_VERSION: 8.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - uses: actions/checkout@v4
    
    # Setup .NET Sdk
    - name: Setup .NET 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    # Check File Structure
    - run: ls -R
  
    # Restore dependencies
    - name: Install dependencies
      run: dotnet restore ./Catalog.API/Catalog.API.csproj
    