name: Build and Publish .NET Application to App Service

on:
    push:
    workflow_dispatch:

env:
    DOTNET_VERSION: 8.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - uses: actions/checkout@v4
    
    # Setup .NET Sdk
    - name: Setup .NET 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    # Check Directory Structure
    - run: ls -R
  
    # Restore dependencies
    - name: Install dependencies
      run: dotnet restore ./Catalog.API/Catalog.API.csproj
    
    # Run dotnet build
    - name: Build with dotnet
      run: dotnet build ./Catalog.API/Catalog.API.csproj --configuration Release --no-restore

    # Run dotnet publish and store the artifacts in catalog/publish
    - name: Publish
      run: |
        dotnet publish ./Catalog.API/Catalog.API.csproj --configuration Release --no-build --output 'catalog/publish'
    
    # Check Directory Structure
    - run: ls -R
  
    # Upload Artifacts
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: catalog-app
        path: 'catalog/publish'      # The directory from where the artifact has to be uploaded.
                                     # Since we published the output to catalog/publish, the package resides there.

  deploy-to-dev:
    runs-on: ubuntu-latest
    
    needs: [build]
    
    steps:
    #Download the artifact named catalog-app to a specified path ./publish. This will first create
    #the directory./publish and then download the artifact with name dotnet-app to that directory
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: catalog-app
        path: './publish'

    # Check Directory Structure
    - run: ls -R